ComicVines
vegaj/iweb-python pull request #9
Opened 2019-01-16 23:44 UTC by vegaj

La api se procesa en el lado del servidor porque comicvines no tiene cors permitido.

2019-01-16 23:46 UTC, vegaj commented
Para probarlo teneis que poner la clave de la api.

2019-01-17 11:32 UTC, alvaroReina requested changes
El código parece correcto pero no se ajusta a lo pedido en esta feature, revisa las comentarios sobre los archivos modificados

2019-01-17 11:32 UTC, alvaroReina commented on src/app.yaml
> +  FLIKR_KEY: "YOUR FLICKR API KEY"
Es necesaria la variable FLIKR_KEY para usar la api ComicVine?

2019-01-17 11:39 UTC, vegaj commented
> El código parece correcto pero no se ajusta a lo pedido en esta feature, revisa las comentarios sobre los archivos modificados

Voy a eliminar la entrada de Flickr

- [ ] Eliminar entrada de Flickr en app.yaml

2019-01-17 11:42 UTC, vegaj commented on src/app.yaml
> +  FLIKR_KEY: "YOUR FLICKR API KEY"
```suggestion
env_variables:
  COMIC_KEY: "YOUR COMICVINE API KEY"
```

2019-01-17 11:43 UTC, alvaroReina approved these changes

2019-01-17 11:47 UTC, merged